tests: migrate arm64 build to podman
For some reason, using docker makes the build fail.
Even though the image daemon-base is well built, the build for the image 'demo'
fails because it doesn't find the demon-base image.

Using podman instead of docker allows to get around this issue.

```
=== docker build quay.io/ceph/demo:demo-centos-stream8-aarch64
running cmd: sleep 30
running cmd: docker images
REPOSITORY                   TAG                     IMAGE ID       CREATED          SIZE
quay.io/ceph/daemon-base     demo-centos-8-aarch64   c280c09c778f   36 seconds ago   1.18GB
buildpack-deps               buster                  7ceeb7ee443c   11 days ago      802MB
buildpack-deps               bullseye                af4a6a6182dd   11 days ago      833MB
debian                       10                      1df4474660a1   11 days ago      114MB
debian                       11                      35073ea3b0b7   11 days ago      124MB
node                         18                      0f9df951673d   2 weeks ago      1.09GB
node                         18-alpine               9112cb38e57e   2 weeks ago      176MB
moby/buildkit                latest                  869c7038a926   3 weeks ago      172MB
node                         16                      81c6e5ef93fc   4 weeks ago      909MB
ubuntu                       20.04                   14be0685b768   5 weeks ago      72.8MB
ubuntu                       22.04                   5a81c4b8502e   5 weeks ago      77.8MB
node                         16-alpine               d22e42cbfdbb   6 weeks ago      118MB
alpine                       3.16                    5cb2da5c2391   7 weeks ago      5.54MB
alpine                       3.17                    1f73a9d63274   7 weeks ago      7.05MB
alpine                       3.18                    c1aabb73d233   7 weeks ago      7.33MB
ubuntu                       18.04                   f9a80a55f492   2 months ago     63.2MB
node                         14                      1d12470fa662   3 months ago     912MB
node                         14-alpine               0dac3dc27b1a   4 months ago     119MB
multiarch/qemu-user-static   latest                  3539aaa87393   6 months ago     305MB
running cmd: docker build -t quay.io/ceph/demo:demo-centos-stream8-aarch64 .

------
 > [internal] load metadata for quay.io/ceph/daemon-base:demo-centos-8-aarch64:
------
Dockerfile:1
--------------------
   1 | >>> FROM quay.io/ceph/daemon-base:demo-centos-8-aarch64
   2 |
   3 |     ENV I_AM_IN_A_CONTAINER 1
--------------------
ERROR: failed to solve: quay.io/ceph/daemon-base:demo-centos-8-aarch64: quay.io/ceph/daemon-base:demo-centos-8-aarch64: not found
make[1]: *** [Makefile:30: build] Error 1
make[1]: Leaving directory '/home/runner/work/ceph-container/ceph-container/staging/main-centos-arm64-8-x86_64/demo'
make: *** [Makefile:68: do.image.x86_64,main,centos-arm64,8] Error 2
Error: Process completed with exit code 2.
```

Signed-off-by: Guillaume Abrioux <gabrioux@ibm.com>