maint-lib: improve error handling
I think the following error is not very helpful:

```
[vagrant@ci-1 ceph-container]$ DEBUG=1 make BASEOS_REGISTRY=quay.io/centos BASEOS_TAG=stream9 RELEASE="$(git rev-parse --short HEAD)" FLAVORS="main,centos,9" IMAGES_TO_BUILD="daemon-base" stage

  CEPH_VERSION      : main
  CEPH_REF          : main
  CEPH_POINT_RELEASE:
  CEPH_DEVEL        : false
  OSD_FLAVOR        : default
  DISTRO            : centos
  DISTRO_VERSION    : 9
  HOST_ARCH         : x86_64
  BASEOS_REGISTRY   : quay.io/centos
  BASEOS_REPO       : centos
  BASEOS_TAG        : stream9
  IMAGES_TO_BUILD   : daemon-base
  STAGING_DIR       : staging/main-centos-9-x86_64
  RELEASE           : 2fb63752
  DAEMON_BASE_IMAGE : quay.io/ceph/daemon-base:2fb63752-main-centos-stream9-x86_64
  DAEMON_IMAGE      : quay.io/ceph/daemon:2fb63752-main-centos-stream9-x86_64
  DEMO_IMAGE        : quay.io/ceph/demo:2fb63752-main-centos-stream9-x86_64

Computed:
  BASE_IMAGE        : quay.io/centos/centos:stream9

Traceback (most recent call last):
  File "maint-lib/stage.py", line 117, in <module>
    main(CORE_FILES_DIR, CEPH_RELEASES_DIR)
  File "maint-lib/stage.py", line 108, in main
    do_variable_replace(replace_root_dir=os.path.join(STAGING_DIR, image))
  File "/home/vagrant/ceph-container/maint-lib/stagelib/replace.py", line 131, in do_variable_replace
    total_replacements, rendered_text = _do_replace_on_file(file_path, replace_root_dir)
  File "/home/vagrant/ceph-container/maint-lib/stagelib/replace.py", line 93, in _do_replace_on_file
    rendered_text, file_path, variable_file_dir=replace_root_dir)
  File "/home/vagrant/ceph-container/maint-lib/stagelib/replace.py", line 61, in _file_replace
    template_text, file_path)
  File "/home/vagrant/ceph-container/maint-lib/stagelib/replace.py", line 35, in _replace_file_in_text
    with open(variable_file_path) as variable_file:
FileNotFoundError: [Errno 2] No such file or directory: 'staging/main-centos-9-x86_64/daemon-base/__ENABLE_REPOS__'
make: *** [Makefile:63: stage.x86_64,main,centos,9] Error 1
```

Having a clear message pointing out what file is missing is slightly more meaningful:

```
[vagrant@ci-1 ceph-container]$ DEBUG=1 make BASEOS_REGISTRY=quay.io/centos BASEOS_TAG=stream9 RELEASE="$(git rev-parse --short HEAD)" FLAVORS="main,centos,9" IMAGES_TO_BUILD="daemon-base" stage

  CEPH_VERSION      : main
  CEPH_REF          : main
  CEPH_POINT_RELEASE:
  CEPH_DEVEL        : false
  OSD_FLAVOR        : default
  DISTRO            : centos
  DISTRO_VERSION    : 9
  HOST_ARCH         : x86_64
  BASEOS_REGISTRY   : quay.io/centos
  BASEOS_REPO       : centos
  BASEOS_TAG        : stream9
  IMAGES_TO_BUILD   : daemon-base
  STAGING_DIR       : staging/main-centos-9-x86_64
  RELEASE           : 2fb63752
  DAEMON_BASE_IMAGE : quay.io/ceph/daemon-base:2fb63752-main-centos-stream9-x86_64
  DAEMON_IMAGE      : quay.io/ceph/daemon:2fb63752-main-centos-stream9-x86_64
  DEMO_IMAGE        : quay.io/ceph/demo:2fb63752-main-centos-stream9-x86_64

Computed:
  BASE_IMAGE        : quay.io/centos/centos:stream9

File staging/main-centos-9-x86_64/daemon-base/__ENABLE_REPOS__ is missing

make: *** [Makefile:63: stage.x86_64,main,centos,9] Error 1
[vagrant@ci-1 ceph-container]$
```

Signed-off-by: Guillaume Abrioux <gabrioux@ibm.com>
Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>