travis/demo: Change sree port to 5001
Both Ceph REST API and SREE use port 5000. This results by a port
conflict when the ceph rest api tries to start.

++/opt/ceph-container/bin/demo.sh:277: bootstrap_rest_api(): ceph-rest-api --cluster test -c /etc/ceph/test.conf -n client.admin
 * Running on http://[::]:5000/
Traceback (most recent call last):
  File "/usr/bin/ceph-rest-api", line 53, in <module>
    app.run(host=app.ceph_addr, port=app.ceph_port)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 772, in run
    run_simple(host, port, self, **options)
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 710, in run_simple
    inner()
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 692, in inner
    passthrough_errors, ssl_context).serve_forever()
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 486, in make_server
    passthrough_errors, ssl_context)
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 410, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "/usr/lib64/python2.7/SocketServer.py", line 419, in __init__
    self.server_bind()
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib64/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use

This patch changes the SREE port for the demo to 5001.

Signed-off-by: Dimitri Savineau <dsavinea@redhat.com>