tests: Retry rm'ing container
Example where this would be needed:
```
docker rm -f 4fcd7c2012b6
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
time="2022-08-09T17:22:11Z" level=error msg="container \"4fcd7c2012b63e6bf9bffd9b7d490d12f1d557ba924e889192ec858821019d91\" does not exist"

Error: cannot remove container 4fcd7c2012b63e6bf9bffd9b7d490d12f1d557ba924e889192ec858821019d91 as it could not be stopped: timed out waiting for file /tmp/podman-run-1111/libpod/tmp/exits/4fcd7c2012b63e6bf9bffd9b7d490d12f1d557ba924e889192ec858821019d91: internal libpod error
docker rm -f 4fcd7c2012b6
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
ERRO[0000] Joining network namespace for container 4fcd7c2012b63e6bf9bffd9b7d490d12f1d557ba924e889192ec858821019d91: error retrieving network namespace at /tmp/podman-run-1111/netns/netns-600d6718-1a5e-2fed-bf39-ad7048004be2: unknown FS magic on "/tmp/podman-run-1111/netns/netns-600d6718-1a5e-2fed-bf39-ad7048004be2": ef53
4fcd7c2012b63e6bf9bffd9b7d490d12f1d557ba924e889192ec858821019d91
```

See https://github.com/containers/podman/issues/13227

This also makes the function fail fatally.

Signed-off-by: David Galloway <dgallowa@redhat.com>