daemon: resolve broken package dependancy
Error:  nfs-ganesha-fsal : Depends: glusterfs-common (>= 3.8.8) but it
is not going to be installed

Solution: temporary remove the package and re-introduce it once the
issue is resolved.

This is urgent as this breaks all the builds on Xenial.

Signed-off-by: Sébastien Han <seb@redhat.com>