Do not die if lock does not exist
I'm getting these errors on mon containers, which should be fixed with this patch:

    Error:  100: Key not found (/ceph-config/ceph/lock) [108]

Signed-off-by: Jairo Llopis <yajo.sk8@gmail.com>