contrib: Do not show HEAD ref in git ls-remote
When the latest tag is the same than the HEAD ref we have two refs to
that tag causing the script to not build the avaiblable tag.

$ git ls-remote --tags
(...)
4101899ab55e916ad7da625daf330d6ea5a11d09	refs/tags/v4.0.0rc1
15d8573c1d9dfedbda9ca012f3609497704e34af	refs/tags/v4.0.0rc1^{}

This build script will then throw an error like:

+ echo 'ERROR: it looks like more than one tag are not built, see
v4.0.0rc1 v4.0.0rc1.'
ERROR: it looks like more than one tag are not built, see v4.0.0rc1
v4.0.0rc1.
+ git checkout 'refs/tags/v4.0.0rc1 v4.0.0rc1'
error: pathspec 'refs/tags/v4.0.0rc1 v4.0.0rc1' did not match any
file(s) known to git.
++ git branch -r --contains 'tags/v4.0.0rc1 v4.0.0rc1'
++ grep -Eo 'stable-[0-9].[0-9]'
error: malformed object name tags/v4.0.0rc1 v4.0.0rc1

Using the --refs option with git ls-remote will not display the HEAD
ref.

Signed-off-by: Dimitri Savineau <dsavinea@redhat.com>