daemon: fix dmcrypt activation for bluestore
When using bluestore with dmcrypt each encrypted partition needs to
opened so the OSD can run normally.
Basically prior to this commit, the code wasn't supporting opening encrypted bluestore devices.

This prevents the following error:

mount: unknown filesystem type 'crypto_LUKS'
Traceback (most recent call last):
  File "/usr/sbin/ceph-disk", line 9, in <module>
    load_entry_point('ceph-disk==1.0.0', 'console_scripts', 'ceph-disk')()
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 5704, in run
    main(sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 5655, in main
    args.func(args)
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 3759, in main_activate
    reactivate=args.reactivate,
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 3499, in mount_activate
    path = mount(dev=dev, fstype=fstype, options=mount_options)
  File "/usr/lib/python2.7/dist-packages/ceph_disk/main.py", line 1449, in mount
    raise MountError(e)
ceph_disk.main.MountError: Mounting filesystem failed: Command '['/bin/mount', '-t', u'crypto_LUKS', '-o', '', '--', '/dev/sdb1', '/var/lib/ceph/tmp/mnt.ReDJVo']' returned non-zero exit status 32

Signed-off-by: Sébastien Han <seb@redhat.com>