tests: Use old increment method
Jenkins adds spaces which makes the function exit 1.

Fixes:
```
++ docker ps -a -q
+ containers_to_remove=10eb12ab5f5e
+ '[' 10eb12ab5f5e ']'
+ ATTEMPTS=0
++ docker ps -a -q
++ wc -l
+ NUM_CONTAINERS=1
+ '[' 0 -eq 5 ']'
+ '[' 1 -eq 0 ']'
+ docker rm -f 10eb12ab5f5e
10eb12ab5f5ef303c62c71bfe3b04d7b33f42d50289f415b1665e1b2e72cce09
+ (( ATTEMPTS++ ))
ERROR: InvocationError for command /usr/bin/bash tests/tox.sh (exited with code 1)
```

Signed-off-by: David Galloway <dgallowa@redhat.com>